"""자동생성 코드 제외 검증."""
from cpguard.generated import GeneratedCodePolicy

GEN = """// @generated by protoc. DO NOT EDIT.
function f(req){ child_process.exec(req.query.c); }
"""
HAND = """// 사람이 쓴 파일
function f(req){ child_process.exec(req.query.c); }
"""
MARKED = """// generated wrapper
/* start of user code */
const a = 1;
/* end of user code */
const b = 2;
"""


def test_detects_generated_header():
    p = GeneratedCodePolicy()
    assert p.is_generated_file(GEN)
    assert not p.is_generated_file(HAND)


def test_disabled_policy_excludes_nothing():
    p = GeneratedCodePolicy(enabled=False)
    assert not p.is_generated_file(GEN)
    assert not p.excludes(GEN, 2)


def test_user_code_markers():
    p = GeneratedCodePolicy(start_marker="start of user code",
                            end_marker="end of user code")
    keep = p.user_code_lines(MARKED)
    assert keep == {3}          # const a = 1 만 사용자 코드
    assert not p.excludes(MARKED, 3)
    assert p.excludes(MARKED, 5)  # 마커 밖


def test_no_markers_returns_none():
    p = GeneratedCodePolicy(start_marker="start of user code",
                            end_marker="end of user code")
    assert p.user_code_lines(HAND) is None


def test_filter_findings_removes_generated():
    from cpguard.parse import loader, normalize
    from cpguard.taint import engine
    from cpguard.taint.spec import load_rules
    from cpguard.generated import filter_findings

    mod = normalize.normalize(loader.parse_source(GEN), file="g.js")
    fs = engine.analyze(mod, GEN.encode(), load_rules(language="javascript"))
    assert fs, "샘플에 취약점이 있어야 한다"
    kept, removed = filter_findings(fs, {"g.js": GEN}, GeneratedCodePolicy())
    assert kept == [] and removed == len(fs)
