"""자동생성 코드 구간 판별.

코드 생성기가 만든 파일(ORM 스텁, 프로토콜 바인딩, 빌드 산출물)에서 나온 알람은
개발자가 고칠 수 없는 코드를 지적하는 것이라 노이즈가 된다. 상용 SAST 들이
"사용자 코드 구간" 마커로 이를 걸러내는 것과 같은 방식을 쓴다.

동작
  - 파일 전체가 생성물임을 알리는 헤더 주석이 있으면 파일 전체 제외.
  - start/end 마커가 있으면 그 사이(사용자 코드)만 남기고 바깥을 제외.
설정이 없으면 아무것도 제외하지 않는다(기본은 끄기).
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field

# 파일 전체가 자동생성임을 나타내는 흔한 헤더 표현
FILE_MARKERS = (
    "@generated",
    "auto-generated",
    "autogenerated",
    "automatically generated",
    "do not edit",
    "generated by",
    "코드 자동 생성",
)
HEADER_LINES = 10  # 헤더로 볼 앞부분 줄 수


@dataclass
class GeneratedCodePolicy:
    """자동생성 코드 제외 정책."""
    enabled: bool = True
    start_marker: str | None = None   # 예: "start of user code"
    end_marker: str | None = None     # 예: "end of user code"
    file_markers: tuple[str, ...] = field(default_factory=lambda: FILE_MARKERS)

    def is_generated_file(self, src: str) -> bool:
        if not self.enabled:
            return False
        head = "\n".join(src.splitlines()[:HEADER_LINES]).lower()
        return any(m.lower() in head for m in self.file_markers)

    def user_code_lines(self, src: str) -> set[int] | None:
        """start/end 마커가 있으면 사용자 코드 줄번호(1-indexed) 집합, 없으면 None."""
        if not self.enabled or not (self.start_marker and self.end_marker):
            return None
        lines = src.splitlines()
        inside = False
        keep: set[int] = set()
        found = False
        for i, line in enumerate(lines, 1):
            if self.start_marker in line:
                inside, found = True, True
                continue
            if self.end_marker in line:
                inside = False
                continue
            if inside:
                keep.add(i)
        return keep if found else None

    def excludes(self, src: str, line: int) -> bool:
        """이 위치의 알람을 제외해야 하는가."""
        if not self.enabled:
            return False
        if self.is_generated_file(src):
            return True
        keep = self.user_code_lines(src)
        return keep is not None and line not in keep


def filter_findings(findings, sources: dict[str, str], policy: GeneratedCodePolicy):
    """sink 위치가 자동생성 구간인 finding 을 걸러낸다. 반환: (남은 것, 제외 수)."""
    if not policy.enabled:
        return findings, 0
    kept, removed = [], 0
    for f in findings:
        src = sources.get(f.sink.loc.file)
        if src is not None and policy.excludes(src, f.sink.loc.start_line):
            removed += 1
            continue
        kept.append(f)
    return kept, removed
