# Generated by Django 5.2.17 on 2026-09-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("file_count", models.IntegerField(default=0)),
                ("finding_count", models.IntegerField(default=0)),
                ("findings_json", models.TextField(default="[]")),
                ("sarif_json", models.TextField(default="{}")),
                (
                    "triage_note",
                    models.CharField(blank=True, default="", max_length=500),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
