# Generated by Django 5.2.17 on 2026-09-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="integrity_note",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
