# Generated by Django 5.2.17 on 2026-09-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_scan_integrity_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="audit_json",
            field=models.TextField(default="{}"),
        ),
        migrations.AddField(
            model_name="scan",
            name="sources_json",
            field=models.TextField(default="{}"),
        ),
    ]
