# Generated by Django 5.2.17 on 2026-09-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_scan_audit_json_scan_sources_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="new_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scan",
            name="project",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="scan",
            name="resolved_count",
            field=models.IntegerField(default=0),
        ),
    ]
