# Generated by Django 5.2.17 on 2026-09-03 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_scan_new_count_scan_project_scan_resolved_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="FindingRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idx", models.IntegerField()),
                ("severity", models.CharField(db_index=True, max_length=12)),
                ("rule_id", models.CharField(db_index=True, max_length=100)),
                ("cwe", models.CharField(blank=True, default="", max_length=24)),
                ("owasp", models.CharField(blank=True, default="", max_length=100)),
                ("file", models.CharField(db_index=True, max_length=600)),
                ("line", models.IntegerField(default=0)),
                (
                    "fp",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=40
                    ),
                ),
                ("category", models.CharField(blank=True, default="", max_length=20)),
                ("verdict", models.CharField(blank=True, default="", max_length=20)),
                ("message", models.TextField(blank=True, default="")),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="web.scan",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["scan", "severity"],
                        name="web_finding_scan_id_fa4992_idx",
                    ),
                    models.Index(
                        fields=["scan", "rule_id"],
                        name="web_finding_scan_id_2a5b5e_idx",
                    ),
                ],
            },
        ),
    ]
