# Generated by Django 5.2.17 on 2026-09-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_findingrow"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="audit_notes_json",
            field=models.TextField(default="{}"),
        ),
    ]
