# Generated by Django 5.2.17 on 2026-09-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0007_scan_severity_counts"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="standards",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
