# Generated by Django 5.2.17 on 2026-09-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_scan_standards"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="code_lines",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scan",
            name="languages",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
