# Generated by Django 5.2.17 on 2026-09-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0009_scan_code_lines_scan_languages"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project", models.CharField(max_length=200, unique=True)),
                ("exclude_globs", models.TextField(blank=True, default="")),
                ("exclude_rules", models.TextField(blank=True, default="")),
                ("note", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.AddField(
            model_name="scan",
            name="scan_config_json",
            field=models.TextField(blank=True, default="{}"),
        ),
    ]
