# Generated by Django 5.2.17 on 2026-09-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0010_projectsetting_scan_scan_config_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="stats_json",
            field=models.TextField(blank=True, default="{}"),
        ),
    ]
