# Generated by Django 5.2.17 on 2026-09-07 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0011_scan_stats_json"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idx", models.IntegerField()),
                ("before", models.CharField(blank=True, default="", max_length=20)),
                ("after", models.CharField(blank=True, default="", max_length=20)),
                ("at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.CharField(blank=True, default="", max_length=100)),
                ("bulk", models.BooleanField(default=False)),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="web.scan",
                    ),
                ),
            ],
            options={
                "ordering": ["-at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["scan", "idx"], name="web_auditev_scan_id_3d763a_idx"
                    )
                ],
            },
        ),
    ]
