# Generated by Django 5.2.17 on 2026-09-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0012_auditevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "title_override",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "header_note",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("logo_path", models.CharField(blank=True, default="", max_length=500)),
                (
                    "references",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("include_detail", models.BooleanField(default=True)),
                ("include_source", models.BooleanField(default=True)),
                ("include_comment", models.BooleanField(default=True)),
                ("include_exclusions", models.BooleanField(default=True)),
                ("include_rule_list", models.BooleanField(default=True)),
                ("include_scope", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
